window.CLIENTS=[
  {
    "slug": "01-premium-beauty",
    "name": "Premium Beauty",
    "city": "Москва",
    "niche": "Салон красоты",
    "rating": 4.5,
    "reviews": 42,
    "phone": "+7 495 915-37-37",
    "address": "ул. Станиславского, 11",
    "type": "beauty"
  },
  {
    "slug": "02-see-beauty-clinic",
    "name": "See Beauty Clinic",
    "city": "Москва",
    "niche": "Косметологическая клиника",
    "rating": 4.8,
    "reviews": 132,
    "phone": "+7 495 664-34-38",
    "address": "3-я Ямского Поля ул., 9к4",
    "type": "medical"
  },
  {
    "slug": "03-moscow-dental-clinic",
    "name": "Moscow Dental Clinic",
    "city": "Москва",
    "niche": "Стоматология",
    "rating": 4.4,
    "reviews": 9,
    "phone": "+7 499 397-88-88",
    "address": "ул. Вавилова, 79/1",
    "type": "medical"
  },
  {
    "slug": "04-pecheniy-design",
    "name": "Студия дизайна «Печёный»",
    "city": "Москва",
    "niche": "Дизайн интерьера",
    "rating": 4.8,
    "reviews": 51,
    "phone": "+7 915 450-10-00",
    "address": "Мясницкая ул., 42, стр. 3",
    "type": "build"
  },
  {
    "slug": "05-kitchen-concept",
    "name": "Kitchen Concept",
    "city": "Москва",
    "niche": "Кухни на заказ",
    "rating": 4.5,
    "reviews": 15,
    "phone": "8 800 555-70-18",
    "address": "ул. Серпуховский Вал, 21 к2",
    "type": "build"
  },
  {
    "slug": "06-daviani-spa",
    "name": "Daviani beauty & SPA",
    "city": "Москва",
    "niche": "Салон красоты / SPA",
    "rating": 4.1,
    "reviews": 33,
    "phone": "+7 495 191-10-39",
    "address": "Трубная пл., 2",
    "type": "beauty"
  },
  {
    "slug": "07-beautyway-clinic",
    "name": "BEAUTYWAY CLINIC",
    "city": "Москва",
    "niche": "Косметология",
    "rating": 4.9,
    "reviews": 275,
    "phone": "+7 499 393-36-16",
    "address": "Страстной б-р, 4",
    "type": "medical"
  },
  {
    "slug": "08-dental-clinic",
    "name": "Dental Clinic",
    "city": "Москва",
    "niche": "Стоматология",
    "rating": 5,
    "reviews": 9,
    "phone": "+7 495 215-56-45",
    "address": "Большая Марфинская ул., 4к2",
    "type": "medical"
  },
  {
    "slug": "09-archdetali",
    "name": "АрхДетали",
    "city": "Москва",
    "niche": "Дизайн интерьера",
    "rating": 4.9,
    "reviews": 71,
    "phone": "+7 495 921-37-00",
    "address": "Нахимовский пр., 24 к4",
    "type": "build"
  },
  {
    "slug": "10-kitchen-buro",
    "name": "Kitchen Buro",
    "city": "Москва",
    "niche": "Кухни на заказ",
    "rating": 4.6,
    "reviews": 95,
    "phone": "",
    "address": "Холодильный пер., 3к1с4",
    "type": "build"
  },
  {
    "slug": "11-persona-premium",
    "name": "Персона Premium",
    "city": "Москва",
    "niche": "Премиальный салон",
    "rating": 4.7,
    "reviews": 13,
    "phone": "+7 903 790-34-35",
    "address": "Пресненская наб., 8 стр. 1",
    "type": "beauty"
  },
  {
    "slug": "12-md-clinic",
    "name": "МD Клиника",
    "city": "Москва",
    "niche": "Косметология",
    "rating": 4.8,
    "reviews": 56,
    "phone": "+7 495 228-00-54",
    "address": "наб. Тараса Шевченко, 3 к3",
    "type": "medical"
  },
  {
    "slug": "13-american-russian-dental",
    "name": "Американо-российский стоматологический центр",
    "city": "Москва",
    "niche": "Стоматология",
    "rating": 4.8,
    "reviews": 41,
    "phone": "+7 495 797-97-59",
    "address": "Садовая-Кудринская ул., 21А стр.2",
    "type": "medical"
  },
  {
    "slug": "14-archstyle",
    "name": "ArchStyle",
    "city": "Москва",
    "niche": "Дизайн интерьера / ремонт",
    "rating": 5,
    "reviews": 42,
    "phone": "+7 916 903-92-06",
    "address": "1-я Брестская ул., 33 стр.2",
    "type": "build"
  },
  {
    "slug": "15-zetta",
    "name": "Фабрика кухни ZETTA",
    "city": "Москва",
    "niche": "Кухни / мебель",
    "rating": 4.4,
    "reviews": 224,
    "phone": "+7 495 101-19-19",
    "address": "Расторгуевский пер., 1",
    "type": "build"
  },
  {
    "slug": "16-expat-salon",
    "name": "Expat Salon",
    "city": "Москва",
    "niche": "Салон красоты",
    "rating": 4.9,
    "reviews": 101,
    "phone": "+7 906 780-74-37",
    "address": "3-я Тверская-Ямская ул., 21/23",
    "type": "beauty"
  },
  {
    "slug": "17-ihc",
    "name": "IHC — клиника косметологии и трихологии",
    "city": "Москва",
    "niche": "Косметология / трихология",
    "rating": 4.8,
    "reviews": 130,
    "phone": "+7 495 049-22-69",
    "address": "Большой Факельный пер., 3 стр.2",
    "type": "medical"
  },
  {
    "slug": "18-dental-art",
    "name": "Дентал Арт",
    "city": "Москва",
    "niche": "Стоматология",
    "rating": 4.8,
    "reviews": 35,
    "phone": "+7 495 106-22-44",
    "address": "Садовническая ул., 11 стр.2",
    "type": "medical"
  },
  {
    "slug": "19-geometrium",
    "name": "Geometrium",
    "city": "Москва",
    "niche": "Дизайн интерьера / архитектура",
    "rating": 4.8,
    "reviews": 217,
    "phone": "+7 495 401-73-05",
    "address": "Нижняя Сыромятническая ул., 10 стр.8",
    "type": "build"
  },
  {
    "slug": "20-stylish-kitchens",
    "name": "Стильные Кухни",
    "city": "Москва",
    "niche": "Кухни / мебель",
    "rating": 4.5,
    "reviews": 99,
    "phone": "8 800 100-44-22",
    "address": "Кутузовский просп., 36А",
    "type": "build"
  },
  {
    "slug": "21-nebo",
    "name": "Строительная компания Небо",
    "city": "Москва",
    "niche": "Ремонт / строительство",
    "rating": 4.5,
    "reviews": 848,
    "phone": "+7 495 414-11-77",
    "address": "Одесская ул., 2кС",
    "type": "build"
  },
  {
    "slug": "22-loft-concept",
    "name": "Loft Concept",
    "city": "Москва",
    "niche": "Мебель / интерьер",
    "rating": 4.8,
    "reviews": 357,
    "phone": "+7 495 120-46-66",
    "address": "Нижняя Сыромятническая ул., 11 стр.Б2",
    "type": "build"
  },
  {
    "slug": "23-international-school-moscow",
    "name": "The International School of Moscow",
    "city": "Москва",
    "niche": "Международная школа",
    "rating": null,
    "reviews": null,
    "phone": "+7 499 922-44-00",
    "address": "Крылатская ул., 12",
    "type": "school"
  },
  {
    "slug": "24-epam-law",
    "name": "EPAM Law",
    "city": "Москва",
    "niche": "Юридическая фирма",
    "rating": 4.5,
    "reviews": 24,
    "phone": "+7 495 935-80-10",
    "address": "1-я Тверская-Ямская ул., 21",
    "type": "legal"
  },
  {
    "slug": "25-prime-auto-club",
    "name": "PRIME AUTO CLUB",
    "city": "Москва",
    "niche": "Детейлинг / автоуслуги",
    "rating": 4.4,
    "reviews": 31,
    "phone": "+7 910 000-88-83",
    "address": "Ленинградский пр-т., 36",
    "type": "auto"
  },
  {
    "slug": "26-new-moscow-build",
    "name": "Строительная компания «Новая Москва»",
    "city": "Москва",
    "niche": "Строительство",
    "rating": 4.8,
    "reviews": 56,
    "phone": "+7 495 120-99-10",
    "address": "ул. Бачуринская, 8А стр.1",
    "type": "build"
  },
  {
    "slug": "27-roomer",
    "name": "ROOMER",
    "city": "Москва",
    "niche": "Мебельный центр",
    "rating": 4.4,
    "reviews": 5439,
    "phone": "+7 495 568-05-68",
    "address": "ул. Ленинская Слобода, 26",
    "type": "build"
  },
  {
    "slug": "28-brookes-moscow",
    "name": "Brookes Moscow",
    "city": "Москва",
    "niche": "Частная международная школа",
    "rating": null,
    "reviews": null,
    "phone": "+7 499 110-70-01",
    "address": "Лазоревый пр-д, 7",
    "type": "school"
  },
  {
    "slug": "29-extradition-law",
    "name": "Extradition Law Firm",
    "city": "Москва",
    "niche": "Юридическая фирма",
    "rating": 4.8,
    "reviews": 17,
    "phone": "+7 995 260-41-47",
    "address": "Павелецкая наб., 8Б",
    "type": "legal"
  },
  {
    "slug": "30-gold-detailing",
    "name": "GOLD DETAILING PREMIUM",
    "city": "Москва",
    "niche": "Детейлинг",
    "rating": null,
    "reviews": null,
    "phone": "+7 923 999-88-88",
    "address": "Жуков пр., 19",
    "type": "auto"
  },
  {
    "slug": "31-moscowhome",
    "name": "MoscowHome",
    "city": "Московская область",
    "niche": "Строительство частных домов",
    "rating": 5,
    "reviews": 1,
    "phone": "+7 495 762-99-66",
    "address": "с. Успенское, д. 34",
    "type": "build"
  },
  {
    "slug": "32-charm-design",
    "name": "Шарм Дизайн",
    "city": "Москва",
    "niche": "Мебельная фабрика",
    "rating": 4.2,
    "reviews": 82,
    "phone": "+7 495 995-58-87",
    "address": "ул. Складочная, 15",
    "type": "build"
  },
  {
    "slug": "33-eis-southwest",
    "name": "English International School Moscow South West",
    "city": "Москва",
    "niche": "Международная школа",
    "rating": null,
    "reviews": null,
    "phone": "+7 495 668-70-50",
    "address": "ул. Лобачевского, 14",
    "type": "school"
  },
  {
    "slug": "34-kshevitskii-law",
    "name": "Stanislav Kshevitskii — юридические услуги",
    "city": "Москва",
    "niche": "Юридические услуги",
    "rating": 5,
    "reviews": 14,
    "phone": "+7 911 601-04-17",
    "address": "пл. Киевского Вокзала, 2",
    "type": "legal"
  },
  {
    "slug": "35-premium-wash",
    "name": "Премиум-мойка / Detailing центр",
    "city": "Москва",
    "niche": "Автомойка / детейлинг",
    "rating": 4.1,
    "reviews": 16,
    "phone": "+7 929 983-39-91",
    "address": "Боровское ш., 14",
    "type": "auto"
  },
  {
    "slug": "36-gint-m",
    "name": "Гинт-М",
    "city": "Москва",
    "niche": "Строительная компания",
    "rating": 5,
    "reviews": 13,
    "phone": "+7 495 967-94-90",
    "address": "Анненская ул., 17 стр.1",
    "type": "build"
  },
  {
    "slug": "37-woodcraftstudio",
    "name": "WoodCraftStudio",
    "city": "Москва",
    "niche": "Мебель на заказ",
    "rating": 4.7,
    "reviews": 49,
    "phone": "+7 495 023-13-01",
    "address": "Нижняя Сыромятническая ул., 10с2",
    "type": "build"
  },
  {
    "slug": "38-eis-west",
    "name": "English International School Moscow West",
    "city": "Москва",
    "niche": "Международная школа",
    "rating": null,
    "reviews": null,
    "phone": "+7 495 984-59-92",
    "address": "Молодогвардейская ул., 9",
    "type": "school"
  },
  {
    "slug": "39-tarasenko-law",
    "name": "Vasiliy Tarasenko — адвокат",
    "city": "Москва",
    "niche": "Юридические услуги",
    "rating": 5,
    "reviews": 30,
    "phone": "+7 909 961-19-09",
    "address": "Зубовский б-р, 4 стр.1",
    "type": "legal"
  },
  {
    "slug": "40-premium-polish",
    "name": "PREMIUM POLISH",
    "city": "Москва",
    "niche": "Детейлинг / полировка",
    "rating": null,
    "reviews": null,
    "phone": "+7 926 599-39-17",
    "address": "проезд Одоевского, 2А",
    "type": "auto"
  },
  {
    "slug": "41-event-bright",
    "name": "Event Bright",
    "city": "Москва",
    "niche": "Свадебное агентство",
    "rating": 5,
    "reviews": 22,
    "phone": "+7 925 003-11-10",
    "address": "Мясницкая ул., 40 стр.1",
    "type": "event"
  },
  {
    "slug": "42-lucky-agency",
    "name": "Lucky Agency",
    "city": "Москва / МО",
    "niche": "Event-агентство",
    "rating": 5,
    "reviews": 1,
    "phone": "+7 926 898-55-80",
    "address": "КП Парк Авеню, д.122, оф.5",
    "type": "event"
  },
  {
    "slug": "43-mgu-russian",
    "name": "MGU RUSSIAN",
    "city": "Москва",
    "niche": "Языковая школа",
    "rating": 4.9,
    "reviews": 215,
    "phone": "+7 985 761-98-85",
    "address": "Милютинский пер., 15 стр.2А",
    "type": "school"
  },
  {
    "slug": "44-auditkey",
    "name": "АудитКей",
    "city": "Москва",
    "niche": "Бухгалтерские услуги",
    "rating": 5,
    "reviews": 12,
    "phone": "+7 499 325-79-07",
    "address": "Мясницкая ул., 15",
    "type": "legal"
  },
  {
    "slug": "45-emc-schepkina",
    "name": "Европейский медицинский центр — Щепкина",
    "city": "Москва",
    "niche": "Медицинский центр",
    "rating": 4,
    "reviews": 247,
    "phone": "+7 499 688-81-17",
    "address": "ул. Щепкина, 35",
    "type": "medical"
  },
  {
    "slug": "46-love-carrot",
    "name": "Любовь-Морковь",
    "city": "Москва",
    "niche": "Свадебное агентство",
    "rating": 4.8,
    "reviews": 25,
    "phone": "+7 495 741-12-52",
    "address": "Большая Никитская ул., 46/17с1",
    "type": "event"
  },
  {
    "slug": "47-event-pro",
    "name": "Event Pro",
    "city": "Москва",
    "niche": "Event-агентство",
    "rating": 5,
    "reviews": 6,
    "phone": "+7 938 524-31-81",
    "address": "Можайское ш., 5",
    "type": "event"
  },
  {
    "slug": "48-windsor-school",
    "name": "Школа английского языка Виндзор",
    "city": "Москва",
    "niche": "Школа английского языка",
    "rating": 4.6,
    "reviews": 56,
    "phone": "+7 499 322-34-03",
    "address": "Комсомольский пр., 7",
    "type": "school"
  },
  {
    "slug": "49-rosco",
    "name": "RosCo",
    "city": "Москва",
    "niche": "Консалтинг / бухгалтерия",
    "rating": 4.6,
    "reviews": 11,
    "phone": "+7 499 444-00-00",
    "address": "1-й Волконский пер., 13с2",
    "type": "legal"
  },
  {
    "slug": "50-moscow-clinic",
    "name": "Московская клиника",
    "city": "Москва",
    "niche": "Медицинский центр",
    "rating": 4.7,
    "reviews": 197,
    "phone": "+7 495 183-99-54",
    "address": "Полковая ул., 12 к1",
    "type": "medical"
  }
];